import "~/styles/globals.css";
import localFont from "next/font/local";

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "~/components/layout/navbar";
import { Sidebar } from "~/components/layout/sidebar";
import { RightSidebar } from "~/components/sidebar/right-sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = localFont({
  src: "../../public/fonts/Spotify Mix Regular.ttf",
  variable: "--font-circular-light",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${font.variable} font-circular-light font-sans`}
    >
      <body>
        <TRPCReactProvider>
          <Navbar />

          <div className="grid grid-cols-4 gap-2 p-2 pt-0">
            <Sidebar />

            <div className="col-span-2">{children}</div>

            <RightSidebar />
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
